In [6]:
import pandas as pd
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\.csv file\messy_retail_sales_dataset.csv")

In [7]:
df

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Unit_Price,Cost_Price,Discount_%,Payment_Method,Sales_Rep,Revenue,Total_Cost,Profit
0,ORD1001,1/21/2023,Diana,East,Sofa,Home,7,1299,1029.84,0,Transfer,John,9093,7208.88,1884.12
1,ORD1002,12/26/2023,Grace,West,Table,Home,3,1487,1258.70,15,Transfer,Aisha,4461,3776.10,684.90
2,ORD1003,11/7/2023,Grace,East,Sofa,Home,6,348,289.88,5,Card,John,2088,1739.28,348.72
3,ORD1004,2/18/2023,Grace,West,Rice,Groceries,1,26,13.07,0,Cash,Aisha,26,13.07,12.93
4,ORD1005,3/11/2023,Faith,North,Headphones,Electronics,3,1272,937.42,10,Cash,David,3816,2812.26,1003.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,ORD1798,12/16/2023,Grace,South,Laptop,Electronics,1,507,406.03,0,Transfer,Mary,507,406.03,100.97
798,ORD1799,4/15/2023,Ethan,East,Jacket,Clothing,7,1097,952.50,10,Card,David,7679,6667.50,1011.50
799,ORD1800,10/4/2023,Faith,North,Jacket,Clothing,9,1725,935.23,10,Transfer,Mary,15525,8417.07,7107.93
800,ORD1115,1/20/2023,Unknown,West,Jeans,Clothing,6,840,562.95,0,Card,David,5040,3377.70,1662.30
801,ORD1555,7/26/2023,Faith,East,Chair,Home,1,175,92.33,0,Transfer,Aisha,175,92.33,82.67

In [9]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Unit_Price,Cost_Price,Discount_%,Payment_Method,Sales_Rep,Revenue,Total_Cost,Profit
0,ORD1001,2023-01-21,Diana,East,Sofa,Home,7,1299,1029.84,0,Transfer,John,9093,7208.88,1884.12
1,ORD1002,2023-12-26,Grace,West,Table,Home,3,1487,1258.70,15,Transfer,Aisha,4461,3776.10,684.90
2,ORD1003,2023-11-07,Grace,East,Sofa,Home,6,348,289.88,5,Card,John,2088,1739.28,348.72
3,ORD1004,2023-02-18,Grace,West,Rice,Groceries,1,26,13.07,0,Cash,Aisha,26,13.07,12.93
4,ORD1005,2023-03-11,Faith,North,Headphones,Electronics,3,1272,937.42,10,Cash,David,3816,2812.26,1003.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,ORD1798,2023-12-16,Grace,South,Laptop,Electronics,1,507,406.03,0,Transfer,Mary,507,406.03,100.97
798,ORD1799,2023-04-15,Ethan,East,Jacket,Clothing,7,1097,952.50,10,Card,David,7679,6667.50,1011.50
799,ORD1800,2023-10-04,Faith,North,Jacket,Clothing,9,1725,935.23,10,Transfer,Mary,15525,8417.07,7107.93
800,ORD1115,2023-01-20,Unknown,West,Jeans,Clothing,6,840,562.95,0,Card,David,5040,3377.70,1662.30
801,ORD1555,2023-07-26,Faith,East,Chair,Home,1,175,92.33,0,Transfer,Aisha,175,92.33,82.67

In [10]:
print(df.head())

  Order_ID Order_Date Customer_Name Region     Product     Category  Quantity  \
0  ORD1001 2023-01-21         Diana   East        Sofa         Home         7
1  ORD1002 2023-12-26         Grace   West       Table         Home         3
2  ORD1003 2023-11-07         Grace   East        Sofa         Home         6
3  ORD1004 2023-02-18         Grace   West        Rice    Groceries         1
4  ORD1005 2023-03-11         Faith  North  Headphones  Electronics         3

   Unit_Price  Cost_Price  Discount_% Payment_Method Sales_Rep  Revenue  \
0        1299     1029.84           0       Transfer      John     9093
1        1487     1258.70          15       Transfer     Aisha     4461
2         348      289.88           5           Card      John     2088
3          26       13.07           0           Cash     Aisha       26
4        1272      937.42          10           Cash     David     3816

   Total_Cost   Profit
0     7208.88  1884.12
1     3776.10   684.90
2     1739.28   348.72
3       13.07    12.93
4     2812.26  1003.74

In [ ]:
#Total Revenue & Profit

In [11]:
total = df[['Revenue', 'Profit']].sum()
print("Total Revenue & Profit")
print(total)

Total Revenue & Profit
Revenue    4055064.00
Profit     1189604.13
dtype: float64

In [14]:
total.to_csv("total_revenue_profit.csv", header = True)

In [ ]:
#Revenue by Region

In [19]:
revenue_region = df.groupby('Region')['Revenue'].sum().sort_values(ascending = False).head(10)
print("Revenue by Region")
print(revenue_region)

Revenue by Region
Region
East     1043616
West     1025946
North    1001675
South     983827
Name: Revenue, dtype: int64

In [23]:
revenue_region.to_csv("revenue by region.csv")

In [ ]:
#Top products by Revenue

In [24]:
top_products = df.groupby('Product')['Revenue'].sum().sort_values(ascending = False).head(10)
print("Top 10 Products by Revenue")
print(top_products)

Top 10 Products by Revenue
Product
Milk          433148
Jacket        402608
Laptop        372536
Headphones    353734
Jeans         348245
Table         345632
Rice          344699
Phone         322347
Bread         307318
Shirt         283124
Name: Revenue, dtype: int64

In [25]:
top_products.to_csv("top_products.csv")

In [ ]:
#Monthly Revenue Trend

In [26]:
monthly_revenue = df.groupby(df['Order_Date'].dt.to_period('M'))['Revenue'].sum()
print("Monthly Revenue Trend")
print(monthly_revenue)

Monthly Revenue Trend
Order_Date
2023-01    313489
2023-02    280085
2023-03    358977
2023-04    466163
2023-05    427566
2023-06    297029
2023-07    339161
2023-08    403967
2023-09    323585
2023-10    308356
2023-11    234299
2023-12    302387
Freq: M, Name: Revenue, dtype: int64

In [27]:
monthly_revenue.to_csv("montthly_revenue_trend.csv")

In [ ]:
#Profit analysis

In [29]:
profit_analysis = df.groupby('Category')['Profit'].sum().sort_values(ascending = False)
print("Profit Analysis Breakdown")
print(profit_analysis)

Profit Analysis Breakdown
Category
Groceries      319701.60
Electronics    304836.08
Clothing       301719.90
Home           263346.55
Name: Profit, dtype: float64

In [31]:
profit_analysis.to_csv("profit_analysis_breakdown.csv")